// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr0sKdkb9AhtdGKYlMDYDJ5zLQ6MMHh0U',
    appId: '1:586026468938:web:6bc0740b515bf139df08b3',
    messagingSenderId: '586026468938',
    projectId: 'drishtixveda',
    authDomain: 'drishtixveda.firebaseapp.com',
    storageBucket: 'drishtixveda.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY_dD13OKHHTvrEWnwKGQHV5QBa6IckwI',
    appId: '1:586026468938:android:8eaa301ecbbd61b0df08b3',
    messagingSenderId: '586026468938',
    projectId: 'drishtixveda',
    storageBucket: 'drishtixveda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyEaWxVvI1r5RwdZek99hu7dRg8soAvfE',
    appId: '1:586026468938:ios:0deb0858a78a81dddf08b3',
    messagingSenderId: '586026468938',
    projectId: 'drishtixveda',
    storageBucket: 'drishtixveda.firebasestorage.app',
    iosBundleId: 'com.example.drishtixveda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyEaWxVvI1r5RwdZek99hu7dRg8soAvfE',
    appId: '1:586026468938:ios:0deb0858a78a81dddf08b3',
    messagingSenderId: '586026468938',
    projectId: 'drishtixveda',
    storageBucket: 'drishtixveda.firebasestorage.app',
    iosBundleId: 'com.example.drishtixveda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr0sKdkb9AhtdGKYlMDYDJ5zLQ6MMHh0U',
    appId: '1:586026468938:web:8b393af8013b58f7df08b3',
    messagingSenderId: '586026468938',
    projectId: 'drishtixveda',
    authDomain: 'drishtixveda.firebaseapp.com',
    storageBucket: 'drishtixveda.firebasestorage.app',
  );
}
